spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  datasource:
    username: teacher_assistant_backend
    password: q9TEAweN24aQ5uPvVN5
    url: jdbc:postgresql://localhost:5432/teacher_assistant
    driver-class-name: org.postgresql.Driver

application:
  resources:
    messages:
      default-locale: ${RESOURCES_LOCALE:ru-RU}
      prefixes:
        document-management-message-source: by.ezubkova.teacher-assistant.document-management
        journal-module-message-source: by.ezubkova.teacher-assistant.journal
        user-management-module-message-source: by.ezubkova.teacher-assistant.user-management
  messages:
    prefixes:
      document-management: by.ezubkova.teacher-assistant.document-management.
    default-locale: ${LOCALE:ru-RU}
  configuration-properties:
    document-management:
      reports:
        conclusive-progress-report:
          min-document-margin: 0.5  # in centimeters
          max-document-margin: 2  # in centimeters
          default-font-location: fonts/times.ttf
          total-marks-columns: 10
          total-columns: 19
          tracks-per-page: 4