spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/teacher_assistant?currentSchema=library
    username: teacher_assistant_backend
    password: 2Rulu46f1SFbIMKPwF2nYDak
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB


app-config:
  attachments:
    storage:
      base-path: ${ATTACHMENTS_BASE_DIR:C:\TA}



